### ISSUE TITLE
Fabric Server Crash When BMM Installed

### ISSUE THREAD

**Issue by NousYeCuites** [MiraculixxT/bluemap-marker#13]
See log, serveur crash at startup when BMM is in the mod list, doesn't crash when it isn't there
Using Bluemap 3.17 with Bluemap Offline Player Marker 2.6 and Silk 1.10.2,the BMM version was 1.5.1.

Tried with and without Bluemap Offline Player Marker and it still crashes

[2023-10-18-7.log](https://github.com/MiraculixxT/bluemap-marker/files/13035442/2023-10-18-7.log)

**Comment by MiraculixxT** [comment]
It seems like BMM loads a wrong version of adventure (a library it i use). Did you use the [1.5.1](https://modrinth.com/plugin/bmarker/version/1.5.1-fabric-2) version for 1.20.2? I cannot verify that from the code because both have the same version number internally.

If yes, i need to find out why or if modrinth switched back the file. A user reported this after release of this version and i swapped it out in place

**Comment by NousYeCuites** [comment]
Hi, yes its the 1.5.1 from modrinth, the same you linked!

**Comment by MiraculixxT** [comment]
Alright, Modrinth seems to reverted the change i made to the jar file. I uploaded a new fresh version (1.5.2) with the bumped adventure version. Sorry for the issues!

**Comment by NousYeCuites** [comment]
Just tried with 1.5.2 and its works, thanks!
