### ISSUE TITLE
Feature: Abillity to Copy properties of markers to a new marker

### ISSUE THREAD

**Issue by HStep20** [MiraculixxT/bluemap-marker#3]
First off, incredible plugin. It took a few minutes to really understand how to use it, but its so powerful I cant imagine using anything else. 

Praise aside, the biggest problem I have with it now is the inability to edit markers. I know its on the possible roadmap if this amazing plugin gets continued support, but making a small mistake while making a big area marker and having to go back and fix it later is a pain. 

As an interim solution, what about the ability to copy a marker's properties to a new marker? It would allow someone to 'edit' a marker by creating a copy, updating the things they want to change (fill opacity got me twice now on a big area, and the height got me once), while leaving all of the other info like Description, Name, and Edges alone so you don't need to trace out the area for the 4th time.  

--------------------------------------------

Obviously, if this is as 'complex' as adding the ability to Edit a marker, that would be the preferable solution, but Ill leave the decision to you.

**Comment by MiraculixxT** [comment]
Thank you for your kind words :)

Your idea how to implement it sounds interesti

**Comment by MiraculixxT** [comment]
Thank you for your kind words :)

I think editing a marker should be the same effort like cloning a marker, but it sounds very interesting to add anyways. I'll try to find some time in the next days (exam time...) to implement both.

Sadly i'm struggling with multiversion support, because my command system (i use minecrafts inbuilded) do not work in other versions than the one implemented (1.19.2 for this project). Currently that is on top of my todo list

**Comment by MiraculixxT** [comment]
Added :)
https://modrinth.com/mod/bmarker
