### ISSUE TITLE
Plugin somehow using old marker data

### ISSUE THREAD

**Issue by DlljsCodes** [MiraculixxT/bluemap-marker#40]
It seems that the plugin has started using marker data from before the 2.0.0 migration. I can tell because markers I add a few days ago have disappeared, and markers I deleted a few months ago have reappeared.

Even after renaming the `marker` folder in the `plugins/BlueMap-Marker` directory and restarting the server, the old markers still appear.

Using BMM 2.1.5 on Paper 1.21.1.

**Comment by MiraculixxT** [comment]
Since 2.0 all markers in paper are stored in the folder `plugins/BMMarker/...`. If you migrated your old markers, you can delete the old folder to avoid unwanted migrations.

Editing files while the server is running also result in weird duplications of files. If you already renamed all folders, search for one that looks inside like the following and rename it back to `BMMarker` while the server is offline (the backup folder may not exist for you).
![grafik](https://github.com/user-attachments/assets/7ea44a85-be2c-41a5-aa4c-846bcd77c83e)

**Comment by DlljsCodes** [comment]
All fixed! I had to rename the `BlueMap-Marker` folder to `BMMarker`. There was already a `BMMarker` folder in the `plugins` directory but I renamed it to something else just in case. No idea how that happened...
